### PR TITLE
Strawberry Gem Recipe App

### PR DESCRIPTION
**Pull request by huseyinbiyik**
On this project @nedjwab and @huseyinbiyik worked together.
You can find the features added for this Pull Request below. 🧩
<hr>

- Gitflow structure created and followed.
-  'Devise' installed and used for authentication.
- 'cancancan' installed and used for authorization.
- RSpec and Capybara testing libraries added and installed.
-  The layout of the wireframes provided is used for the user interface.
- Login page and registration page:
    - built with Devise.
- Food list:
    - Display a list of food added by the logged-in user as in the wireframe (for teams with only 2 people - display also quantity of a given food).
    - Leading to a form that allows users to add new food.
- Recipes list:
    - Displaying a list of recipes created by the logged-in user as in the wireframe.
    - leading to recipe details.
    - If the user is the owner of the recipe, allow the user to delete it.
- Public recipe list:
    - Displaying a list of all public recipes ordered by the newest as in the wireframe.
    - Leads to recipe details.
- Recipe details:
    - If the recipe is public or the user is the owner of the recipe, display the recipe details as in the wireframe.
    - If the user is the owner of the recipe, lead to the form that allows the user to add new food.
- General shopping list view
    - Shows the list of food that is missing for all recipes of the logged-in user (compare the list of food for all recipes with the general food list of that user).
    - Counts the total food items and total price of the missing food.
- Made sure there are no N+1 queries happening.
- Created a navigation menu that allows users to open all of the pages you created.

Thank you for your review in advance! 🤓

### CODE REVIEW

**Review by prolajumokeoni — CHANGES_REQUESTED** [review]
Hi @nedjwab and @huseyinbiyik, 
Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✔️ No linter errors
✔️ Git flow was correctly used
✔️  Good design
✔️  Good PR title and Description



## Required Changes ♻️

- [ ] Kindly make sure that Unit and Integration tests written are passing currently they are all falling when I run them locally, when the tests pass locally on your  end, please add to your readme the appropriate instructions  on how  to test your app, see screenshot below👍🏿 
Screenshot_450



_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by huseyinbiyik** [comment]
Hey @prolajumokeoni,
Thank you for the feedback and the review. I don't experience any issues on macOS with the tests. My tests are passing like below.

https://user-images.githubusercontent.com/25887253/190461121-5376c434-8728-47e3-b88a-dd1727877488.mov

**Comment by nedjwab** [comment]
### hi @prolajumokeoni Thank you for your review.
I'm using windows and my tests are passing without facing any issues.
Capturetest

**Comment by prolajumokeoni** [comment]
Hi Team, when I ran the tests it was failing hopefully the next reviewer does not encounter this issue, I enjoyed reviewing your project, keep up the good work 🤗

**Review by ShahierNashaat — APPROVED** [review]
Hi @nedjwab, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## To Highlight 💯 

- All tests are passing ✔️
- Correct use of GitFlow ✔️
- Descriptive commit messages ✔️
- Professional looking pull request ✔️
- Your readme looks professional ✔️
- Good overall design ✔️
- Your code is clean and well documented ✔️

# Approved :ok_hand: :ok_hand: :ok_hand:

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
